### ISSUE TITLE
Data Analysis

### ISSUE THREAD

**Issue by timeforchang** [JIC8202/jic8202.github.io#11] opened 2018-09-15 00:10 UTC
As a database builder, I want to build a graph of influence between scientists and authors by analyzing Wikipedia data so that the graph can be displayed to the user.

Scenario 1:
Given a database of Wikipedia page links, a list of scientists, and a list of authors,
When the link analyzer program is executed,
Then the program should search the page links database for links from scientists to authors to form a graph, which is output as a list of nodes and edges in JSON format.

**Comment by the-skid** [comment] 2018-09-15 05:43
Why was a new issue created for this? This is a duplicate of #2.

**Comment by the-skid** [comment] 2018-09-15 06:17
Updated to reflect the current status of the data analysis pipeline.

This should be done (see [JIC8202/wikipedia-tools](https://github.com/JIC8202/wikipedia-tools)), so I'm closing this.

**Closed by the-skid** 2018-09-15 06:17 UTC
Labels: backend, mvp, priority
